// Package persistence manages Research Loop's plain-text state files.
// All state lives in Markdown and JSONL — human-readable, git-diffable, LLM-resumable.
package persistence

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/research-loop/research-loop/internal/hypothesis"
)

// Session represents one research investigation directory.
type Session struct {
	ID   string // slugified paper title
	Root string // absolute path to session directory
}

// NewSession creates a new session directory under the workspace.
func NewSession(workspaceRoot, paperTitle string) (*Session, error) {
	id := slugify(paperTitle)
	root := filepath.Join(workspaceRoot, ".research-loop", "sessions", id)
	if err := os.MkdirAll(root, 0755); err != nil {
		return nil, fmt.Errorf("creating session dir: %w", err)
	}
	return &Session{ID: id, Root: root}, nil
}

// LoadSession opens an existing session by ID.
func LoadSession(workspaceRoot, id string) (*Session, error) {
	root := filepath.Join(workspaceRoot, ".research-loop", "sessions", id)
	if _, err := os.Stat(root); err != nil {
		return nil, fmt.Errorf("session %q not found", id)
	}
	return &Session{ID: id, Root: root}, nil
}

// WriteHypothesis writes hypothesis.md to the session directory.
func (s *Session) WriteHypothesis(h *hypothesis.Hypothesis) error {
	content := renderHypothesisMarkdown(h)
	return os.WriteFile(filepath.Join(s.Root, "hypothesis.md"), []byte(content), 0644)
}

// WriteKnowledgeGraph creates an initial empty knowledge_graph.md.
func (s *Session) WriteKnowledgeGraph(paperTitle string) error {
	content := fmt.Sprintf(`# Knowledge Graph — %s

> Living DAG of every hypothesis tried, result observed, and causal annotation written.
> Generated by Research Loop · %s

## Status

Session initialized. No experiments run yet.

## Hypothesis Space

- [ ] Initial hypothesis (see hypothesis.md)

## Explored Paths

*None yet — experiments will populate this section.*

## Dead Ends

*None yet.*

## Key Learnings

*None yet.*
`, paperTitle, time.Now().Format("2006-01-02"))

	return os.WriteFile(filepath.Join(s.Root, "knowledge_graph.md"), []byte(content), 0644)
}

// WriteLabNotebook creates an initial lab_notebook.md.
func (s *Session) WriteLabNotebook(paperTitle string) error {
	content := fmt.Sprintf(`# Lab Notebook — %s

> Human-readable experiment log. Updated after every run.
> Generated by Research Loop · %s

## Session Initialized

- **Date**: %s
- **Paper**: %s
- **Status**: Awaiting first experiment

---

*Experiments will appear here as they run.*
`, paperTitle, time.Now().Format("2006-01-02"), time.Now().Format("2006-01-02 15:04"), paperTitle)

	return os.WriteFile(filepath.Join(s.Root, "lab_notebook.md"), []byte(content), 0644)
}

// AppendJSONL appends a single record to autoresearch.jsonl.
func (s *Session) AppendJSONL(record map[string]interface{}) error {
	record["timestamp"] = time.Now().UTC().Format(time.RFC3339)

	data, err := json.Marshal(record)
	if err != nil {
		return err
	}

	f, err := os.OpenFile(filepath.Join(s.Root, "autoresearch.jsonl"), os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()

	_, err = fmt.Fprintf(f, "%s\n", data)
	return err
}

// HypothesisPath returns the path to hypothesis.md.
func (s *Session) HypothesisPath() string {
	return filepath.Join(s.Root, "hypothesis.md")
}

// ─── Rendering ───────────────────────────────────────────────────────────────

func renderHypothesisMarkdown(h *hypothesis.Hypothesis) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# Hypothesis — %s\n\n", h.PaperTitle))
	sb.WriteString(fmt.Sprintf("> Generated by Research Loop · %s\n\n", h.GeneratedAt.Format("2006-01-02 15:04")))
	sb.WriteString("---\n\n")

	sb.WriteString("## Paper\n\n")
	sb.WriteString(fmt.Sprintf("- **Title**: %s\n", h.PaperTitle))
	if len(h.PaperAuthors) > 0 {
		sb.WriteString(fmt.Sprintf("- **Authors**: %s\n", strings.Join(h.PaperAuthors, ", ")))
	}
	if h.ArXivID != "" {
		sb.WriteString(fmt.Sprintf("- **ArXiv**: https://arxiv.org/abs/%s\n", h.ArXivID))
	}
	sb.WriteString("\n")

	sb.WriteString("## Core Claim\n\n")
	sb.WriteString(h.CoreClaim + "\n\n")

	sb.WriteString("## Key Insight\n\n")
	sb.WriteString(h.KeyInsight + "\n\n")

	if h.MathFormulation != "" {
		sb.WriteString("## Mathematical Formulation\n\n")
		sb.WriteString(h.MathFormulation + "\n\n")
	}

	sb.WriteString("## Proposed Experiment\n\n")
	sb.WriteString(h.ProposedExperiment + "\n\n")

	sb.WriteString("## Configuration\n\n")
	sb.WriteString(fmt.Sprintf("- **Baseline repo**: `%s`\n", h.BaselineRepo))
	sb.WriteString(fmt.Sprintf("- **Metric**: `%s`\n", h.Metric))
	sb.WriteString("\n")

	sb.WriteString("## Required Skills\n\n")
	sb.WriteString("- [ ] Identify collaborators if any skills are missing\n")
	sb.WriteString("- [ ] Complete idea-selection skill checklist before first experiment\n\n")

	sb.WriteString("## Status\n\n")
	sb.WriteString("- [ ] Hypothesis approved by researcher\n")
	sb.WriteString("- [ ] Baseline repository cloned and validated\n")
	sb.WriteString("- [ ] First experiment loop started\n")

	return sb.String()
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

func slugify(s string) string {
	s = strings.ToLower(s)
	s = nonAlnum.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-")
	if len(s) > 60 {
		s = s[:60]
	}
	// Append date suffix to avoid collisions
	s = s + "-" + time.Now().Format("2006-01-02")
	return s
}
