// Package config manages workspace configuration for Research Loop.
// Config lives at .research-loop/config.toml in the workspace root.
package config

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/viper"
)

const (
	DirName    = ".research-loop"
	ConfigFile = "config.toml"
)

// Config is the top-level workspace configuration.
type Config struct {
	LLM      LLMConfig            `mapstructure:"llm"`
	Agents   AgentsConfig         `mapstructure:"agents"`
	Metric   MetricConfig         `mapstructure:"metric"`
	Workspace WorkspaceConfig     `mapstructure:"workspace"`
}

// LLMConfig configures the default LLM backend.
type LLMConfig struct {
	Provider  string       `mapstructure:"provider"`   // anthropic | openai | ollama
	Model     string       `mapstructure:"model"`
	APIKeyEnv string       `mapstructure:"api_key_env"`
	BaseURL   string       `mapstructure:"base_url"`   // for ollama / openai-compatible
	Fallback  *LLMConfig   `mapstructure:"fallback"`
}

// AgentsConfig allows per-agent model overrides.
type AgentsConfig struct {
	Epistemic LLMConfig `mapstructure:"epistemic"`
	Empirical LLMConfig `mapstructure:"empirical"`
	Scribe    LLMConfig `mapstructure:"scribe"`
}

// MetricConfig declares what to measure.
type MetricConfig struct {
	Name             string `mapstructure:"name"`
	Direction        string `mapstructure:"direction"`         // "lower" | "higher"
	BaselineCommand  string `mapstructure:"baseline_command"`
	BenchmarkCommand string `mapstructure:"benchmark_command"`
	TimeoutSecs      int    `mapstructure:"timeout"`
}

// WorkspaceConfig holds workspace-level settings.
type WorkspaceConfig struct {
	Root string `mapstructure:"root"`
}

// Load reads config from the workspace .research-loop/config.toml.
// If no config exists, it returns sensible defaults.
func Load(workspaceRoot string) (*Config, error) {
	v := viper.New()
	v.SetConfigName("config")
	v.SetConfigType("toml")
	v.AddConfigPath(filepath.Join(workspaceRoot, DirName))

	// Defaults
	v.SetDefault("llm.provider", "anthropic")
	v.SetDefault("llm.model", "claude-sonnet-4-5")
	v.SetDefault("llm.api_key_env", "ANTHROPIC_API_KEY")
	v.SetDefault("metric.direction", "lower")
	v.SetDefault("metric.timeout", 300)

	if err := v.ReadInConfig(); err != nil {
		if _, ok := err.(viper.ConfigFileNotFoundError); !ok {
			return nil, fmt.Errorf("reading config: %w", err)
		}
		// No config file — use defaults, that's fine
	}

	var cfg Config
	if err := v.Unmarshal(&cfg); err != nil {
		return nil, fmt.Errorf("parsing config: %w", err)
	}

	cfg.Workspace.Root = workspaceRoot
	return &cfg, nil
}

// Init creates the .research-loop directory and a default config.toml.
func Init(workspaceRoot string) error {
	dir := filepath.Join(workspaceRoot, DirName)
	for _, sub := range []string{
		dir,
		filepath.Join(dir, "sessions"),
		filepath.Join(dir, "library", "papers"),
		filepath.Join(dir, "bundles"),
		filepath.Join(dir, "skills"),
	} {
		if err := os.MkdirAll(sub, 0755); err != nil {
			return fmt.Errorf("creating directory %s: %w", sub, err)
		}
	}

	cfgPath := filepath.Join(dir, ConfigFile)
	if _, err := os.Stat(cfgPath); err == nil {
		return nil // already exists
	}

	defaultCfg := `# Research Loop configuration
# Generated by research-loop init

[llm]
provider     = "anthropic"
model        = "claude-sonnet-4-5"
api_key_env  = "ANTHROPIC_API_KEY"

# Per-agent model overrides (optional)
# [agents.epistemic]
# model = "claude-sonnet-4-5"
# [agents.empirical]
# model = "claude-haiku-4-5"

[metric]
# karpathy/autoresearch: val_bpb (bits per byte, lower is better)
# Set benchmark_command to the command that runs your experiment.
# The output must contain a line like:  val_bpb:  0.997900
# For autoresearch: uv run train.py > run.log 2>&1
name              = "val_bpb"
direction         = "lower"
benchmark_command = ""
timeout           = 420

# ── autoresearch (karpathy/autoresearch) quickstart ──────────────────────────
# 1. Clone the repo:
#      git clone https://github.com/karpathy/autoresearch
# 2. Set up data (one-time, ~2 min):
#      cd autoresearch && uv run prepare.py
# 3. Set benchmark_command above to:
#      uv run train.py > run.log 2>&1
# 4. Set the repo path when starting the loop:
#      research-loop loop start --repo ./autoresearch
# ─────────────────────────────────────────────────────────────────────────────
`
	return os.WriteFile(cfgPath, []byte(defaultCfg), 0644)
}

// WorkspaceRoot walks up from cwd looking for a .research-loop directory.
// Falls back to cwd if none found.
func WorkspaceRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		return "."
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, DirName)); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	cwd, _ := os.Getwd()
	return cwd
}
